# Generated by Django 3.1.7 on 2021-04-02 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_principle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='principle',
        ),
    ]
